# Generated by Django 4.2.16 on 2025-05-26 23:14

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='', upload_to='profile_image/%Y/%m'),
        ),
    ]
