# Generated by Django 4.2.16 on 2025-05-27 07:18

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profile_image/default.png', null=True, upload_to='profile_image/%Y/%m'),
        ),
    ]
